In [1]:
import pandas as pn;
import numpy as np;
import seaborn as sns;
import matplotlib.pyplot as plt;

In [2]:
wine = pn.read_csv('./Data/Wine.csv');

In [4]:
wine.head()

Alcohol  Malic_Acid  Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0       13           2    6            13        125              1   
1       11           6    4            10        147              3   
2       11           4    3            13         89              2   
3       15           6    6            11        151              4   
4       12           2    3            13        146              0   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity  Hue  \
0           0                  0.71                3                8    1   
1           2                  0.66                4                2    2   
2           4                  0.36                2                3    1   
3           4                  0.54                5               11    1   
4           1                  0.35                2                7    1   

   OD280  Proline  Customer_Segment  
0      1     1004                 1  
1      1      681                 1  
2      3      946                 1  
3      3      319                 1  
4      3     1640                 1

In [5]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
Alcohol                 178 non-null int64
Malic_Acid              178 non-null int64
Ash                     178 non-null int64
Ash_Alcanity            178 non-null int64
Magnesium               178 non-null int64
Total_Phenols           178 non-null int64
Flavanoids              178 non-null int64
Nonflavanoid_Phenols    178 non-null float64
Proanthocyanins         178 non-null int64
Color_Intensity         178 non-null int64
Hue                     178 non-null int64
OD280                   178 non-null int64
Proline                 178 non-null int64
Customer_Segment        178 non-null int64
dtypes: float64(1), int64(13)
memory usage: 19.5 KB


In [8]:
X = wine.values[:, :-1]
y = wine.values[:, -1:]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2);

In [12]:
from sklearn.linear_model import LogisticRegression;

In [13]:
lor = LogisticRegression()

In [14]:
lor.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [15]:
y_pred = lor.predict(X_test);

In [16]:
from sklearn.metrics import confusion_matrix;
from sklearn.metrics import accuracy_score;

In [17]:
confusion_matrix(y_test, y_pred)

array([[ 4, 11,  3],
       [ 3,  5,  1],
       [ 2,  5,  2]])

In [18]:
accuracy_score(y_test, y_pred)

0.3055555555555556

In [88]:
confusion_matrix(y_test, y_pred)

array([[ 4, 11,  3],
       [ 3,  5,  1],
       [ 2,  5,  2]])

In [19]:
#Using DecisionTree
from sklearn.tree import DecisionTreeClassifier;
dtc = DecisionTreeClassifier();

In [20]:
dtc.fit(X_train, y_train);

In [21]:
dt_pred = dtc.predict(X_test)

In [22]:
accuracy_score(y_test, dt_pred)

0.3888888888888889

In [89]:
confusion_matrix(y_test, dt_pred)

array([[7, 5, 6],
       [3, 2, 4],
       [2, 2, 5]])

In [23]:
# Using RandomForest

In [84]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=52, random_state=2)

In [85]:
rfc.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=52, n_jobs=None,
            oob_score=False, random_state=2, verbose=0, warm_start=False)

In [86]:
rf_pred = rfc.predict(X_test)

In [87]:
accuracy_score(y_test, rf_pred)

0.2222222222222222

In [91]:
confusion_matrix(y_test, rf_pred)

array([[ 3, 12,  3],
       [ 2,  3,  4],
       [ 2,  5,  2]])